apollo:
  appid: data-statistics-server
  cluster: dev
  url: "http://localhost:8080"
  namespace: application
  secret: d25eb8f74ff943ada97e7acde26c93ae
naCos:
  address: "127.0.0.1"
  port: 8848
  context-path: "/nacos"
  log-level: debug
  namespace: c1053630-5dff-4d44-b386-74809763f730
  username: nacos
  password: nacos
  group: LOCAL_GROUP
  cluster-name: DEFAULT
  data-id: mine-grpc
